- arguments:
    project_name: mozilla-docker-build-edwin
  project: existing
- action: set_project_framework
  arguments:
    framework: Docker image build
- action: upload_file
  arguments:
    application_filename: /Users/egao/Downloads/ignore.apk
    test_filename: /Users/egao/workspace/combined_workflow_demo/mozilla_bitbar_docker/build/mozilla-docker-20190116T132328.zip
- action: set_device
  arguments:
    device: Docker Builder
