- arguments:
    project_name: mozilla-docker-build-edwin
  project: existing
- action: set_project_framework
  arguments:
    framework: Docker image build
- action: upload_file
  arguments:
    application_filename: dummy.apk
    test_filename: dummy.zip
- action: set_device
  arguments:
    device: Docker Builder
